model_path: /workspace/shangminghao/models/qwen/Qwen3.5-35B-A3B
save_dir: /workspace/shangminghao/models/qwen/Qwen3.5-35B-A3B-W8A8-gptq
num_calibration_samples: 32
max_seq_length: 8192
dataset_id: /workspace/shangminghao/data/flickr30k/flickr30k
dataset_split: test
device_map: auto
seed: 42
preprocessing_num_workers: 2
dataloader_num_workers: 2
